FROM php:8.3-cli

RUN apt-get update && apt-get install -y \
    libzip-dev libicu-dev libgd-dev libpng-dev \
    nodejs npm unzip git curl \
    && docker-php-ext-install zip intl gd pdo pdo_mysql \
    && curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

WORKDIR /app
COPY . .

RUN composer install --optimize-autoloader --no-scripts --no-interaction
RUN npm install && npm run build
RUN php artisan storage:link || true

EXPOSE 8000
CMD php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000