[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_20", "npm"]

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-intl --ignore-platform-req=ext-zip --ignore-platform-req=ext-gd --ignore-platform-req=php --ignore-platform-req=php-64bit",
  "npm install",
  "npm run build"
]

[phases.deploy]
cmds = [
  "php artisan migrate --force",
  "php artisan storage:link",
  "php artisan config:cache",
  "php artisan route:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"