[variables]
PHP_VERSION = "8.3"

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-intl --ignore-platform-req=ext-zip --ignore-platform-req=ext-gd",
  "npm install",
  "npm run build"
]

[phases.deploy]
cmds = [
  "php artisan migrate --force",
  "php artisan storage:link"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"